library(DT)
library(shiny)
library(leaflet)
library(dplyr)
library(shinydashboard)
library(shinythemes)
library(shinyalert)
library(shinyWidgets)
library(osrm)
library(rgdal)
library(sp)
library(sf)
library(viridis)
library(data.table)


data_file <- file.path(getwd(), "staking_data.rds")
pivottable <- file.path(getwd(), "apt_table.rds")
df <- readRDS(data_file)
at <- readRDS(pivottable)